# Generated by Django 5.0.6 on 2024-07-11 03:20

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schoolapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('id', models.UUIDField(default="<module 'uuid' from '/usr/local/lib/python3.12/uuid.py'>", editable=False, primary_key=True, serialize=False)),
                ('relationship', models.CharField(choices=[('FATHER', 'Father'), ('MOTHER', 'Mother'), ('GUARDIAN', 'Guardian')], max_length=30)),
                ('phone', models.CharField(blank=True, max_length=60, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: 05999999999', regex='^(05)\\d{9}$')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('employee_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(choices=[('PRINCIPAL', 'Principal'), ('TEACHER', 'Teacher'), ('ASSISTANT', 'Assistant'), ('COUNSELOR', 'Counselor')], default='Teacher', max_length=30)),
                ('department', models.CharField(choices=[('MATH', 'Math'), ('ENGLISH', 'English'), ('ADMIN', 'Admin'), ('SCIENCE', 'Science'), ('NOTHING', 'N/A')], default='N/A', max_length=30)),
                ('phone', models.CharField(blank=True, max_length=60, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: 05999999999', regex='^(05)\\d{9}$')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('student_id', models.UUIDField(default='<function uuid4 at 0xffffa7aae980>', editable=False, primary_key=True, serialize=False)),
                ('grade_level', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')])),
                ('homeroom_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.staff')),
                ('parents', models.ManyToManyField(to='schoolapp.parents')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
