# Generated by Django 5.0.6 on 2024-08-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parents',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='students',
            name='student_id',
            field=models.UUIDField(default='<function uuid4 at 0xffffa56eee80>', editable=False, primary_key=True, serialize=False),
        ),
    ]
