# Generated by Django 5.0.6 on 2024-07-12 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0004_announcements_events_schools_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignments',
            old_name='student',
            new_name='student_id',
        ),
        migrations.RenameField(
            model_name='assignments',
            old_name='teacher',
            new_name='teacher_id',
        ),
        migrations.RenameField(
            model_name='clubs',
            old_name='students',
            new_name='students_ids',
        ),
        migrations.RenameField(
            model_name='clubs',
            old_name='teachers',
            new_name='teacher_ids',
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='student',
            new_name='student_id',
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='teacher',
            new_name='teacher_id',
        ),
        migrations.RenameField(
            model_name='parents',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='student',
            new_name='student_id',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='teacher',
            new_name='teacher_id',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='school',
            new_name='school_id',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='parents',
            new_name='parent_ids',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='school',
            new_name='school_id',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='announcements',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='date_of_birth',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='student_id',
            field=models.UUIDField(default='<function uuid4 at 0xffff87c128e0>', editable=False, primary_key=True, serialize=False),
        ),
    ]
