

services:
  web:
    env_file:
      - .env
    build: .
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_DB_NAME: ${DJANGO_DB_NAME}
      DJANGO_SU_NAME: ${DJANGO_SU_NAME}
      DJANGO_SU_EMAIL: ${DJANGO_SU_EMAIL}
      DJANGO_SU_PASSWORD: ${DJANGO_SU_PASSWORD}
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      DJANGO_DEBUG: ${DJANGO_DEBUG}
    command: gunicorn mysite.wsgi --bind 0.0.0.0:8001
    depends_on:
      - db
    networks:
      - backend
    

  nginx:
    image: nginx:latest
    networks:
      - backend
    depends_on:
      - web

  db:
    image: postgres
    networks:
      - backend

networks:
  backend:
    driver: bridge